config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :customers

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :set_customer, only: [:edit, :update, :show]

	def index
		@customers = Customer.all
	end

	def new
		@customer = Customer.new
	end

	def show
	end

	def edit
	end

	def update
		if @customer.update(customer_params)
			redirect_to customer_path(@customer.id), notice: 'Cliente atualizado com sucesso!'
		else
			render :edit
		end
	end

	def create
		@customer = Customer.new(customer_params)

		if @customer.save
			redirect_to customers_path, notice: 'Cliente cadastrado com sucesso!'
		else
			render :new
		end
	end

private

	def set_customer
		@customer = Customer.find(params[:id])
	end

	def customer_params
		params.require(:customer).permit(:id, :first_name, :last_name, :email, :phone, :smoker, :avatar)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/edit.html.erb
<% if @customer.errors.any? %>
  <% @customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

<h1>Editar Cliente</h1>

<%= form_for @customer do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.label :smoker %> <br />
  <% {'S': 'Sim','N': 'Não'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %> <br /> 
  <% end %>

  <%= f.submit 'Salvar' %>

<% end %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Sobrenome</td>
      <td>Email</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name %></td>
      <td><%= customer.email %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Cliente', new_customer_path %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <% @customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

<h1>Novo Cliente</h1>

<%= form_for @customer do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.label :smoker %> <br />
  <% {'S': 'Sim','N': 'Não'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %> <br /> 
  <% end %>

  <%= f.submit 'Criar' %>

<% end %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Show</h1>

<%= @customer.first_name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudTdd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<ul>
  <li><%= link_to 'Cadastro de Clientes', customers_path %></li>
</ul>